#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Mar 26, 2022 01:50:43 PM +0700  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import form.gui_support


class Toplevel1:
    def __init__(self, top=None):
        """This class configures and populates the toplevel window.
        top is the toplevel containing window."""
        _bgcolor = "#d9d9d9"  # X11 color: 'gray85'
        _fgcolor = "#000000"  # X11 color: 'black'
        _compcolor = "#d9d9d9"  # X11 color: 'gray85'
        _ana1color = "#d9d9d9"  # X11 color: 'gray85'
        _ana2color = "#ececec"  # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use("winnative")
        self.style.configure(".", background=_bgcolor)
        self.style.configure(".", foreground=_fgcolor)
        self.style.configure(".", font="TkDefaultFont")
        self.style.map(".", background=[("selected", _compcolor), ("active", _ana2color)])

        top.geometry("529x296+318+152")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("dashboard.chipchip.com v1.1")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.btnRun = ttk.Button(self.top)
        self.btnRun.place(relx=0.813, rely=0.034, height=25, width=86)
        self.btnRun.configure(takefocus="")
        self.btnRun.configure(text="""Run""")
        self.btnRun.configure(compound="left")

        self.txtlog = tk.Text(self.top)
        self.txtlog.place(relx=0.019, rely=0.135, relheight=0.679, relwidth=0.958)
        self.txtlog.configure(background="white")
        self.txtlog.configure(font="TkTextFont")
        self.txtlog.configure(foreground="black")
        self.txtlog.configure(highlightbackground="#d9d9d9")
        self.txtlog.configure(highlightcolor="black")
        self.txtlog.configure(insertbackground="black")
        self.txtlog.configure(selectbackground="blue")
        self.txtlog.configure(selectforeground="white")
        self.txtlog.configure(wrap="word")

        self.lbHsd = tk.Label(self.top)
        self.lbHsd.place(relx=0.019, rely=0.912, height=22, width=504)
        self.lbHsd.configure(activebackground="#f9f9f9")
        self.lbHsd.configure(activeforeground="black")
        self.lbHsd.configure(anchor="w")
        self.lbHsd.configure(background="#d9d9d9")
        self.lbHsd.configure(compound="left")
        self.lbHsd.configure(disabledforeground="#a3a3a3")
        self.lbHsd.configure(foreground="#ff0000")
        self.lbHsd.configure(highlightbackground="#d9d9d9")
        self.lbHsd.configure(highlightcolor="black")
        self.lbHsd.configure(text="""...""")

        self.lbFileselect = tk.Label(self.top)
        self.lbFileselect.place(relx=0.019, rely=0.845, height=22, width=504)
        self.lbFileselect.configure(activebackground="#f9f9f9")
        self.lbFileselect.configure(activeforeground="black")
        self.lbFileselect.configure(anchor="w")
        self.lbFileselect.configure(background="#d9d9d9")
        self.lbFileselect.configure(compound="left")
        self.lbFileselect.configure(disabledforeground="#a3a3a3")
        self.lbFileselect.configure(foreground="#0000ff")
        self.lbFileselect.configure(highlightbackground="#d9d9d9")
        self.lbFileselect.configure(highlightcolor="black")
        self.lbFileselect.configure(text="""...""")

        self.btnChonFile = ttk.Button(self.top)
        self.btnChonFile.place(relx=0.019, rely=0.034, height=25, width=86)
        self.btnChonFile.configure(takefocus="")
        self.btnChonFile.configure(text="""Chọn File""")
        self.btnChonFile.configure(compound="left")
        self.btnChonFile.configure(cursor="fleur")


def start_up():
    gui_support.main()


if __name__ == "__main__":
    gui_support.main()
