#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    May 24, 2022 10:15:40 AM +0700  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import form.gui_supportimport customtkinter


class Toplevel1:
    def __init__(self, top=None):
        """This class configures and populates the toplevel window.
        top is the toplevel containing window."""
        _bgcolor = "#d9d9d9"  # X11 color: 'gray85'
        _fgcolor = "#000000"  # X11 color: 'black'
        _compcolor = "#d9d9d9"  # X11 color: 'gray85'
        _ana1color = "#d9d9d9"  # X11 color: 'gray85'
        _ana2color = "#ececec"  # Closest X11 color: 'gray92'
        
        
            
        
        
        
        

        top.geometry("755x467+171+149")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(0, 0)
        top.title("dashboard.chipchip.com v1.1")
        



        self.top = top

        
        
        
        self.TNotebook1 = ttk.Notebook(self.top)
        self.TNotebook1.place(relx=0.008, rely=0.009, relheight=0.955, relwidth=0.981)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t1 = customtkinter.CTkFrame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(
            0,
            text="""Check die mail""",
            compound="left",
            underline="""-1""",
        )



        self.TNotebook1_t2 = customtkinter.CTkFrame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t2, padding=3)
        self.TNotebook1.tab(
            1,
            text="""Lọc mail""",
            compound="left",
            underline="""-1""",
        )




        self.btnChonFile = customtkinter.CTkButton(self.TNotebook1_t1)
        self.btnChonFile.place(relx=0.014, rely=0.786, height=24, width=87)



        self.btnChonFile.configure(compound="left")




        self.btnChonFile.configure(pady="0")
        self.btnChonFile.configure(text="""Chọn file""")

        self.btnRun = customtkinter.CTkButton(self.TNotebook1_t1)
        self.btnRun.place(relx=0.841, rely=0.786, height=24, width=104)



        self.btnRun.configure(compound="left")




        self.btnRun.configure(pady="0")
        self.btnRun.configure(text="""Run""")

        self.txtLog = tk.Text(self.TNotebook1_t1)
        self.txtLog.place(relx=0.0, rely=0.0, relheight=0.757, relwidth=1.012)

        self.txtLog.configure(font="TkTextFont")






        self.txtLog.configure(wrap="word")

        self.txtFileSelect = customtkinter.CTkEntry(self.TNotebook1_t1)
        self.txtFileSelect.place(relx=0.014, rely=0.857, height=20, relwidth=0.969)


        self.txtFileSelect.configure(font="TkFixedFont")







        self.txtHsd = customtkinter.CTkEntry(self.TNotebook1_t1)
        self.txtHsd.place(relx=0.014, rely=0.929, height=20, relwidth=0.969)


        self.txtHsd.configure(font="TkFixedFont")







        self.btnLoc = customtkinter.CTkButton(self.TNotebook1_t2)
        self.btnLoc.place(relx=0.407, rely=0.19, height=24, width=104)



        self.btnLoc.configure(compound="left")




        self.btnLoc.configure(pady="0")
        self.btnLoc.configure(text="""Lọc""")

        self.btnXuatLoc = customtkinter.CTkButton(self.TNotebook1_t2)
        self.btnXuatLoc.place(relx=0.583, rely=0.19, height=24, width=104)



        self.btnXuatLoc.configure(compound="left")




        self.btnXuatLoc.configure(pady="0")
        self.btnXuatLoc.configure(text="""Xuất mail""")

        self.Message1 = tk.Message(self.TNotebook1_t2)
        self.Message1.place(relx=0.027, rely=0.048, relheight=0.045, relwidth=0.122)




        self.Message1.configure(padx="1")
        self.Message1.configure(pady="1")
        self.Message1.configure(text="""Đuôi cần lọc""")
        self.Message1.configure(width=90)

        self.txtDuoiloc = customtkinter.CTkEntry(self.TNotebook1_t2)
        self.txtDuoiloc.place(relx=0.19, rely=0.048, height=20, relwidth=0.738)


        self.txtDuoiloc.configure(font="TkFixedFont")







        self.btnThemnoidungloc = customtkinter.CTkButton(self.TNotebook1_t2)
        self.btnThemnoidungloc.place(relx=0.231, rely=0.19, height=24, width=104)




        self.btnThemnoidungloc.configure(compound="left")




        self.btnThemnoidungloc.configure(pady="0")
        self.btnThemnoidungloc.configure(text="""Thêm mail lọc""")

        self.txtStatusLoc = customtkinter.CTkEntry(self.TNotebook1_t2)
        self.txtStatusLoc.place(relx=0.041, rely=0.31, height=20, relwidth=0.887)



        self.txtStatusLoc.configure(font="TkFixedFont")








def start_up():
    gui_support.main()


if __name__ == "__main__":
    gui_support.main()
