#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  May 24, 2022 10:15:40 AM +0700  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 755x467+171+149
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "dashboard.chipchip.com v1.1"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(complement_color)]
    ttk::notebook $top.tNo47 \
        -width 741 -height 446 -takefocus {} 
    vTcl:DefineAlias "$top.tNo47" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo47.t0 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t0 \
        -padding 0 -sticky nsew -state normal -text {Check die mail} \
        -image {} -compound left -underline -1 
    set site_4_0  $top.tNo47.t0
    button $site_4_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Chọn file} 
    vTcl:DefineAlias "$site_4_0.but48" "btnChonFile" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Run 
    vTcl:DefineAlias "$site_4_0.but49" "btnRun" vTcl:WidgetProc "Toplevel1" 1
    text $site_4_0.tex50 \
        -background white -font TkTextFont -foreground black -height 318 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 746 -wrap word 
    $site_4_0.tex50 configure -font "TkTextFont"
    $site_4_0.tex50 insert end text
    vTcl:DefineAlias "$site_4_0.tex50" "txtLog" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent51 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 714 
    vTcl:DefineAlias "$site_4_0.ent51" "txtFileSelect" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent52 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 714 
    vTcl:DefineAlias "$site_4_0.ent52" "txtHsd" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but48 \
        -in $site_4_0 -x 0 -relx 0.014 -y 0 -rely 0.786 -width 87 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but49 \
        -in $site_4_0 -x 0 -relx 0.841 -y 0 -rely 0.786 -width 104 \
        -relwidth 0 -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tex50 \
        -in $site_4_0 -x 0 -y 0 -width 0 -relwidth 1.012 -height 0 \
        -relheight 0.757 -anchor nw -bordermode ignore 
    place $site_4_0.ent51 \
        -in $site_4_0 -x 0 -relx 0.014 -y 0 -rely 0.857 -width 714 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent52 \
        -in $site_4_0 -x 0 -relx 0.014 -y 0 -rely 0.929 -width 714 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo47.t1 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t1 \
        -padding 0 -sticky nsew -state normal -text {Lọc mail} -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo47.t1
    button $site_4_1.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Lọc 
    vTcl:DefineAlias "$site_4_1.but54" "btnLoc" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Xuất mail} 
    vTcl:DefineAlias "$site_4_1.but55" "btnXuatLoc" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_1.mes57 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -padx 1 -pady 1 -text {Đuôi cần lọc} -width 90 
    vTcl:DefineAlias "$site_4_1.mes57" "Message1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_1.ent58 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 544 
    vTcl:DefineAlias "$site_4_1.ent58" "txtDuoiloc" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_1.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Thêm mail lọc} 
    vTcl:DefineAlias "$site_4_1.but47" "btnThemnoidungloc" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_1.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 654 
    vTcl:DefineAlias "$site_4_1.ent48" "txtStatusLoc" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_1.but54 \
        -in $site_4_1 -x 0 -relx 0.407 -y 0 -rely 0.19 -width 104 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but55 \
        -in $site_4_1 -x 0 -relx 0.583 -y 0 -rely 0.19 -width 104 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.mes57 \
        -in $site_4_1 -x 0 -relx 0.027 -y 0 -rely 0.048 -width 0 \
        -relwidth 0.122 -height 0 -relheight 0.045 -anchor nw \
        -bordermode ignore 
    place $site_4_1.ent58 \
        -in $site_4_1 -x 0 -relx 0.19 -y 0 -rely 0.048 -width 544 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but47 \
        -in $site_4_1 -x 0 -relx 0.231 -y 0 -rely 0.19 -width 104 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.ent48 \
        -in $site_4_1 -x 0 -relx 0.041 -y 0 -rely 0.31 -width 654 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo47 \
        -in $top -x 0 -relx 0.008 -y 0 -rely 0.009 -width 0 -relwidth 0.981 \
        -height 0 -relheight 0.955 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

